version: '2'

services:
  opencart:
    image: enriquecidopg/opencart:1.5.6.4
    ports:
      - "8000:80"
    links:
      - mysql
    restart: always

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=opencart
    restart: always
